import { jsPDF } from 'jspdf';
import { AnalysisResult } from '../types';

export function downloadAnalysisReport(analysis: AnalysisResult) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 16;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('SatQuery AI - Remote Sensing Mission Report', 14, 12);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(
    `Report ID: REP-${analysis.id}  |  Generated: ${new Date().toUTCString()}`,
    14,
    19
  );

  y = 34;

  // Mission Summary Box
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(14, y, pageWidth - 28, 38, 2, 2, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Mission & Query Overview', 18, y + 7);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`User Query: "${analysis.query}"`, 18, y + 14);
  doc.text(`Detected Task: ${analysis.executionSummary?.taskDetected || analysis.task}`, 18, y + 20);
  doc.text(
    `Model Confidence: ${analysis.confidence.toFixed(1)}% (${analysis.confidenceLabel || 'Estimated confidence'})`,
    18,
    y + 26
  );
  doc.text(
    `Remote-Sensing Adaptation: Enabled (Dataset: ${analysis.remoteSensingAdaptation?.dataset || 'BigEarthNet'})`,
    18,
    y + 32
  );

  y += 46;

  // Findings & Specialist Answer
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, y, pageWidth - 28, 48, 2, 2, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Specialist Interpretation & Natural-Language Findings', 18, y + 7);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);

  // Split text to fit width
  const splitAnswer = doc.splitTextToSize(analysis.answer, pageWidth - 36);
  doc.text(splitAnswer, 18, y + 15);

  y += 56;

  // Input Imagery Specifications
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('3. Input Satellite Imagery Specifications', 14, y);
  y += 5;

  (analysis.images || []).forEach((img, idx) => {
    doc.setDrawColor(203, 213, 225);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(14, y, pageWidth - 28, 20, 1, 1, 'FD');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(`Image ${idx + 1}: ${img.filename}`, 18, y + 6);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Format: ${img.format} | Modality: ${img.modality.toUpperCase()} | Dim: ${img.dimensions?.width}x${img.dimensions?.height} | Bands: ${img.bands}`,
      18,
      y + 11
    );
    doc.text(`CRS: ${img.crs || 'EPSG:32643'} | Status: ${img.validationStatus.toUpperCase()}`, 18, y + 16);

    y += 24;
  });

  // Execution Trace Table
  y += 4;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('4. Auditable Agent Execution Trace', 14, y);
  y += 6;

  (analysis.executionSummary?.steps || []).forEach((step) => {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129); // green
    doc.text(`[✓] Step ${step.stepNumber}: ${step.name}`, 16, y);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const detailLines = doc.splitTextToSize(step.detail, pageWidth - 42);
    doc.text(detailLines, 20, y + 4.5);

    y += 9 + (detailLines.length - 1) * 3.5;
  });

  // Footer Disclaimer
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 280, pageWidth - 14, 280);
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text(
    'CONFIDENTIAL & VERIFIED: Generated by SatQuery AI Agentic Remote-Sensing Engine. Confidence is model-estimated.',
    14,
    285
  );

  doc.save(`SatQuery_Analysis_Report_${analysis.id}.pdf`);
}
